flaskProject/models/models.py
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import Enum

# Create the SQLAlchemy database object for use in app
db = SQLAlchemy()

# Class used to create the student and invoice database tables.


class Student(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    studentId = db.Column(db.String(8), unique=True)
    hasOutstandingBalance = db.Column(db.Boolean, default=False)
    invoices = db.relationship(
        "Invoice", backref="student", cascade="all, delete-orphan"
    )
    # Delete orphan invoices if student is deleted.


class Invoice(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    reference = db.Column(db.String(8), unique=True)
    amount = db.Column(db.Float)
    dueDate = db.Column(db.Date)
    studentId = db.Column(
        db.String(8),
        db.ForeignKey(
            "student.studentId", ondelete="CASCADE", name="fk_invoice_student"
        ),
    )
    # Foreign key for invoices, to identify associated student.
    type = db.Column(db.String(15))
    status = db.Column(db.String(15), default="OUTSTANDING")

flaskProject/app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from models.models import *
from controllers.invoiceController import invoiceController
from controllers.studentController import studentController
from controllers.portalController import portalController
from datetime import datetime

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql://root:password@localhost/Invoices'

db.init_app(app)
migrate = Migrate(app, db)

app.register_blueprint(invoiceController)
app.register_blueprint(studentController)
app.register_blueprint(portalController)


@app.route('/')
def hello_world():  # put application's code here
    return 'Hello World!'


if __name__ == '__main__':
    app.run(port=5000)

flaskProject/controllers/invoiceController.py
from flask import Blueprint, render_template, Flask, request, jsonify
from services import invoiceService

invoiceController = Blueprint("invoiceController", __name__)
service = invoiceService.InvoiceService()


@invoiceController.route("/api/invoice/create_invoice", methods=["POST"])
def create_invoice():
    """
    POST API used to create invoices with the microservice.

    Parameters:
    a (Invoice): An invoice to instantiate in the database, allowing payment or cancellation.

    Returns:
    A serialized invoice object that has been created on the finance service.
    """
    invoice = request.json
    # Converting the request into an invoice, to read pertinent information from.
    result = service.create_invoice(invoice)
    serialized_invoice = {
        "reference": result.reference,
        "amount": result.amount,
        "dueDate": result.dueDate.isoformat(),
        "type": result.type,
        "status": result.status,
        "studentId": result.studentId,
    }
    return jsonify(serialized_invoice)

flaskProject/controllers/portalController.py
from flask import Blueprint, render_template, Flask, request, jsonify
from services import invoiceService

portalController = Blueprint("portalController", __name__)
service = invoiceService.InvoiceService()


@portalController.get("/portal")
def portal_get():
    """
    GET endpoint for the portal of the finance service.

    Returns:
    A render template of the portal html page.
    """
    return render_template("portal.html")


@portalController.post("/portal")
def portal_post():
    """
    POST endpoint for the invoice checking page of the finance service.

    Returns:
    A render template of the portal html page if reference isn't found, or to an invoice's html page if it is found.
    """
    reference = request.form.get("reference")
    if service.exists_invoice(reference):
        return render_template("invoice.html", invoice=service.get_invoice(reference))
    else:
        return render_template("portal.html", message="Reference not found.")


@portalController.get("/invoice")
def invoice_get():
    """
    GET endpoint of an invoice page of the finance service.

    Returns:
    A render template of the invoice page of the specified reference.
    """
    reference = request.json["reference"]
    return render_template("invoice.html", invoice=service.get_invoice(reference))


@portalController.post("/invoice")
def invoice_post():
    """
    POST endpoint of an invoice page of the finance service.

    Returns:
    A render template of the invoice page of the specified reference, updating if the invoice has been paid.
    """
    reference = request.form.get("reference")
    service.pay_invoice(reference)
    return render_template("invoice.html", invoice=service.get_invoice(reference))

flaskProject/controllers/studentController.py
from flask import Blueprint, render_template, Flask, request, jsonify
from services import studentService

studentController = Blueprint("studentController", __name__)
service = studentService.StudentService


@studentController.route("/api/get-outstanding-invoices", methods=["POST"])
def get_outstanding_invoices():
    """
    POST endpoint, gets a list of all references for outstanding invoices for a given student ID.

    Parameters:
    a (String): The student ID to receive references for.

    Returns:
    A list of references for all associated invoices that are outstanding.
    """
    student_id = request.json["studentId"]
    print(student_id)
    answer = service.get_outstanding_references(student_id)
    print(answer)
    return jsonify(answer)

flaskProject/templates/invoice.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Student Home Page</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        .container {
            max-width: 700px;
            max-height: 600px;
            top ;
            background-color: #e9ecef;
            border: 1px solid black;
            border-radius: 1px;
            justify-content: center;
            align-items: center;
        }

        .form-group {
            display: flex;
            align-items: center;
            justify-content: center;
            margin-bottom: 1rem;
        }

        .form-group label {
            flex-basis: 100px;
            text-align: left;
        }

        .form-group input {
            flex-grow: 1;
            max-width: 300px;
        }
    </style>
</head>
<body>
<div class="container">
    <h2 style="text-align: center;">Invoice {{ invoice.reference }}</h2>
    <form action="{{ url_for('portalController.invoice_post') }}" method="post">
        <div class="form-group">
            <label for="id">Id</label>
            <input id="id" type="text" name="id" value="{{ invoice.id }}">
        </div>
        <div class="form-group">
            <label for="fee">Fee</label>
            <input id="fee" type="text" name="fee" value="{{ invoice.amount }}">
        </div>
        <div class="form-group">
            <label for="due_date">Due Date</label>
            <input id="due_date" type="text" name="due_date" value="{{ invoice.dueDate }}">
        </div>
        <div class="form-group">
            <label for="type">Invoice Type</label>
            <input id="type" type="text" name="type" value="{{ invoice.type }}">
        </div>
        <div class="form-group">
            <label for="status">Status</label>
            <input id="status" type="text" name="status" value="{{ invoice.status }}">
        </div>
        <div class="form-group">
            <label for="student_id">Student ID</label>
            <input id="student_id" type="text" name="student_id" value="{{ invoice.studentId }}">
        </div>
        <input type="hidden" name="reference" value="{{ invoice.reference }}">
        <div class="form-group">
            <a href="{{ url_for('portalController.portal_get') }}" class="btn btn-primary">View Another Invoice</a>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Pay Invoice</button>
        </div>
    </form>
</div>
</body>
</html>

flaskProject/templates/portal.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Student Home Page</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
<div class="container">
  <h2 class="text-center mt-4">Finance Portal</h2>
  <form action="{{ url_for('portalController.portal_post') }}" method="post" class="mt-4" onsubmit="return validateForm()">
    <div class="form-group">
      <label for="reference">Reference</label>
      <input id="reference" class="form-control" type="text" name="reference">
      <small id="validationMessage" class="text-danger"></small>
    </div>
    <div class="form-group text-center">
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </form>
</div>
{% if message is defined %}
<span style="display: block; margin-top: 10px; text-align: center;">{{ message }}</span>
{% endif %}
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script>
  function validateForm() {
    var referenceInput = document.getElementById("reference");
    var validationMessage = document.getElementById("validationMessage");

    var alphanumericRegex = /^[a-zA-Z0-9]+$/;
    if (referenceInput.value.length !== 8 || !alphanumericRegex.test(referenceInput.value)) {
      validationMessage.innerText = "Reference must be 8 characters long and contain only letters and numbers.";
      return false;
    } else {
      validationMessage.innerText = "";
      return true;
    }
  }
</script>
</body>
</html>